#!/bin/bash
echo "==== complete install QO100 Transceiver ===="
echo "full update, upgrade and installation"
set -e
cd ~
echo "update system by running apt-get update"

sudo apt-get update
echo "install git"
sudo apt-get install git -y
if [ ! -d "QO100_Transceiver" ] ; then
        git clone https://github.com/dj0abr/QO100_Transceiver
        cd QO100_Transceiver
    else
        cd QO100_Transceiver
        git pull https://github.com/dj0abr/QO100_Transceiver
    fi
cd ~/QO100_Transceiver/scripts
./prepare_ubuntu_pluto
cd ~/QO100_Transceiver/scripts
./makeall
echo "==== Installation: OK ===="
cd ~/QO100_Transceiver/Release
echo "==== Start the Transceiver in the folder QO100_Transceiver/Release ===="
echo "==== by entering ./startQO100trx                                   ===="
