#!/bin/sh

# Setup : Put into TDD mode, and setup GPO0 and GPO1
iio_attr -q -a -D ad9361-phy adi,frequency-division-duplex-mode-enable 0
iio_attr -q -a -D ad9361-phy adi,gpo0-slave-rx-enable 1
iio_attr -q -a -D ad9361-phy adi,gpo1-slave-tx-enable 1
iio_attr -q -a -D ad9361-phy  initialize 1

while [ 1 ] ; do
  iio_attr -q -a -d ad9361-phy ensm_mode rx
  # capture buffer
  iio_attr -q -a -d ad9361-phy ensm_mode tx
  # transmit buffer
done

